### ISSUE TITLE
Why the main queue asserts?

### ISSUE THREAD

**Issue by zboralski** [RPallas92/PromisedArchitectureKit#3]
The only time I need to use the main queue is when some code touches UIKit. Most of my UI code sits in the background (thanks to AsyncDisplayKit.)

Since XCode provides a Main Thread Checker I don't see the need for hardcoded asserts.

**Comment by RPallas92** [comment]
Thanks for opening the issue! You are right, that assertion is not needed.

Fixed: https://github.com/RPallas92/PromisedArchitectureKit/pull/4/commits/a322c2d8019fc4b7d4d0b9942a59345f3085699c
